spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hogwarts
    username: student
    password: chocolatefrog
  jpa:
    hibernate:
      ddl: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always